### ISSUE TITLE
[NumberGuesser] Ресурсы

### ISSUE THREAD

**Issue by pavel-b-novikov** [Ningyo/nsudotnet#2]
(пардон, я имел в виду задачу Numberguesser)
А вот перенесите-ка все строки, которые есть в этой задаче в ресурсы и сделайте локализованную версию с возможностью переключения русский/английский.

+2 балла будет в подарок.

**Comment by sfactor** [comment]
(я тут мимо крокодил)

Очень крутые текстовые сообщения!

**Comment by pavel-b-novikov** [comment]
Ау?..

**Comment by Ningyo** [comment]
Строки локализовались, а вот что делать с массивом строк - я пока не пойму о.о Вроде бы неплохо записать из в текстовик, раз уж можно в .resx файлы хранить, а как его потом достать оттуда не пойму .__.

**Comment by pavel-b-novikov** [comment]
Через ResourceManager можно, но это другая история. Чтобы сделать workaroung в текущей версии - просто создавайте этот массив динамически, в методе, доставая строки из текущих ресурсов.

Чтобы протестировать, используйте переключение локали в Thread.CurrentThread.CurrentCulture

А вот делать .GetString вовсе не обязательно.

**Comment by pavel-b-novikov** [comment]
А, ну у вас итак на 5 набирается. Так что можете просто держать последний коммент в голове.
