### ISSUE TITLE
[Enigma] Классы в одном файле

### ISSUE THREAD

**Issue by pavel-b-novikov** [Ningyo/nsudotnet#3]
Не надо так делать, пожалуйста. Разнесите классы по разным файлам

**Comment by Ningyo** [comment]
Действительно о..о Разнесла по классам *и по папкам для красоты*

**Comment by pavel-b-novikov** [comment]
*не лезь вперед батьки в пекло*
Ну коль по разным папкам, то теперь и adjust namespaces сделайте (решарпер могет). Ну и какбэ папки должны называться с большой буквы, ибо конвеншн.
